language: node_js
node_js:
  - "4.0"
before_install:
  - sudo apt-get install libblas*
  - sudo apt-get install liblapack*
  - sudo apt-get install libgsl0-dev
  - wget http://www.netlib.org/lapack/lapack-3.6.1.tgz
  - tar xf lapack-3.6.1.tgz
  - cd lapack-3.6.1/
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DLAPACKE=ON -DCBLAS=ON -DBUILD_SHARED_LIBS=ON  .
  - sudo make install -j2
  - cd ..
install:
  - npm install
env:
  - CXX=g++-4.8
addons:
  code_climate:
    repo_token: 7bc2ff765ac0619975d32fe57959db6374d14a96780a1438ec68ea14036748e1
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - cmake-data
    - gfortran
